import streamlit as st
import pandas as pd
import plotly.express as px
from utils.data_loader import load_raw_data, get_merged_data
from utils.plotting import plot_earthquake_impact, plot_oil_vs_sales, plot_promo_scatter

st.set_page_config(page_title="The Market Story", layout="wide")

st.markdown("# The Market Story")
st.markdown("Understanding the *drivers* of demand before we model.")

# Load Data
with st.spinner("Loading Data..."):
    df = get_merged_data()

if df is None:
    st.stop()

# --- Tabs for Story Arcs ---
tab1, tab2, tab3 = st.tabs(["Earthquake Impact", "Promo Hunter", "Oil & Macro"])

# --- TAB 1: EARTHQUAKE ---
with tab1:
    st.header("The 'Black Swan' Event: April 2016 Earthquake")
    st.info("The earthquake didn't just drop sales; it **shifted** consumption priorities.")
    
    col1, col2 = st.columns([2, 1])
    
    with col1:
        # Geographic Impact
        fig_map = plot_earthquake_impact(df, region_col='state')
        st.plotly_chart(fig_map, use_container_width=True)
    
    with col2:
        st.markdown("### Key Findings")
        st.markdown("""
        - **Manabi** (Epicenter) saw sales surge (+40-50%).
        - **Why?** Aid, rebuilding reserves, and panic buying.
        - **Product Shift**: 
            - **Explosion**: Water, Grains, Cleaning Supplies.
            - **Drop**: Alcohol, Celebrations, Perishables.
        """)
        
        # Mini Dataframe for top growers during crisis
        # (Simple calculation logic similar to research script)
        crisis_start = '2016-04-16'
        crisis_end = '2016-04-30'
        mask = (df['date'] >= crisis_start) & (df['date'] <= crisis_end)
        top_fam = df[mask].groupby('family')['sales'].mean().sort_values(ascending=False).head(5)
        st.write("**Top Sellers during Crisis:**")
        st.dataframe(top_fam)

# --- TAB 2: PROMOS ---
with tab2:
    st.header("Elasticity: The Power of Promotions")
    
    families = df['family'].unique()
    selected_fams = st.multiselect("Select Families to Compare", families, default=['PRODUCE', 'GROCERY I', 'BEVERAGES'])
    
    if selected_fams:
        fig_promo = plot_promo_scatter(df, selected_fams)
        st.plotly_chart(fig_promo, use_container_width=True)
    
    st.success("""
    **Insight**: 
    - **PRODUCE** has extreme elasticity (+200% lift). Fresh food spoils, so promos drive immediate volume.
    - **Cleaning** is less sensitive (people buy when they need it).
    """)

# --- TAB 3: MACRO / OIL ---
with tab3:
    st.header("The Oil Economy Context")
    st.markdown("Ecuador's economy is tied to oil. Does the oil crash (2014-2015) kill sales?")
    
    fig_oil = plot_oil_vs_sales(df)
    st.plotly_chart(fig_oil, use_container_width=True)
    
    st.warning("**Paradox**: As oil prices dropped (2015), retail sales actually **grew**. This negative correlation (-0.75) implies internal inflation or specific retailer expansion strategies masked the macro downturn.")

st.markdown("---")
st.caption("Generated by Antigravity AI")
